### ISSUE TITLE
Failed to resolve: com.esri.arcgis.android:arcgis-android:10.2.9

### ISSUE THREAD

**Issue by xhAndroid** [wshunli/arcgis-android-moremap#2]
无法加载，不知道是什么原因，怎么解决？？

**Comment by wshunli** [comment]
1、可以检查下你的网络，访问 https://esri.bintray.com/arcgis 是否正常
2、可以尝试从官网 https://developers.arcgis.com/android/10-2/ 下载 10.2.9 版本的离线包
